import type { Metadata } from "next";
import Provider from "@/Provider";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import InitUser from "@/InitUser";


export const metadata: Metadata = {
  title: "CrownCart | 10 Minute Delivery App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Assuming favion
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <StoreProvider>
            <InitUser/>
            {children}
          </StoreProvider>
        </Provider>
      </body>
    </html>
  );
}
